import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const PPNeueBit = localFont({
  src: "/fonts/ppneuebit-bold.otf",
  variable: "--font-pp-neuebit",
});

const PPMondWest = localFont({
  src: "/fonts/ppmondwest-regular.otf",
  variable: "--font-pp-mondwest",
});

const PPNeueMontreal = localFont({
  src: "/fonts/ppneuemontreal-medium.otf",
  variable: "--font-pp-neue-montreal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PPNeueBit.variable} ${PPMondWest.variable} ${PPNeueMontreal.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
