import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const PPNeueBit = localFont({
  src: "/fonts/ppneuebit-bold.otf",
  variable: "--font-pp-neuebit",
});

const PPMondWest = localFont({
  src: "/fonts/ppmondwest-regular.otf",
  variable: "--font-pp-mondwest",
});

const PPNeueMontreal = localFont({
  src: "/fonts/ppneuemontreal-medium.otf",
  variable: "--font-pp-neue-montreal",
});

const IBMPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-ibm-plex-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PPNeueBit.variable} ${PPMondWest.variable} ${PPNeueMontreal.variable} ${IBMPlexMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
